### ISSUE TITLE
逆地理编码（坐标转地址），第二次进行坐标转地址失败

### ISSUE THREAD

**Issue by ivan5151** [fluttify-project/amap_search_fluttify#11]
**插件版本**
0.2.13+d2eb645
**描述bug**
逆地理编码（坐标转地址），第二次进行坐标转地址失败
**复现步骤**
首次获取用户当前坐标传入坐标转地址可以正确获取到详细地址，当用户坐标发生变化，传入新的坐标后，无法返回详细地址，但控制台有打印地址
**期望行为**
可以正常返回用户详细地址
**截图**
_getAddress(double lat, double lng) async{
    if(lat > 0 && lng > 0) {
      var latLng = LatLng(
          lat, lng);
      /// 逆地理编码（坐标转地址）
      var reGeocodeList = await AmapSearch.searchReGeocode(
        latLng,
        radius: 200.0,
      );
      if (reGeocodeList != null) {
        var result = await reGeocodeList.formatAddress;
        setState(() {
          _result = result;
        });
        print(result);
      }
    }
  }
**flutter doctor**

**Comment by yohom** [comment]
我在example工程里，改变坐标后能连续获取逆地理信息的。
![7yqp3-7j20t](https://user-images.githubusercontent.com/10418364/69199518-29e15800-0b73-11ea-89a6-db3a69532740.gif)

**Comment by ivan5151** [comment]
我是在地图上移动，后获取到坐标，再转换，没法获取到地址

**Comment by ivan5151** [comment]
AmapView(
          // 地图类型
          mapType: MapType.Standard,
          // 地图语言
          language: Language.Chinese,
          // 是否显示交通情况
          showTraffic: true,
          // 是否显示缩放控件
          showZoomControl: true,
          // 是否显示指南针控件
          showCompass: false,
          // 是否显示定位控件
          //showLocateControl: true,
          // 是否显示比例尺控件
          showScaleControl: true,
          // 是否使能缩放手势
          zoomGesturesEnabled: true,
          // 是否使能滚动手势
          scrollGesturesEnabled: true,
          // 是否使能旋转手势
          rotateGestureEnabled: true,
          // 是否使能倾斜手势
          tiltGestureEnabled: true,
          // 是否使能所有手势
          allGesturesEnabled: true,
          // 缩放级别
          zoomLevel: 17,
          // 中心点坐标
          centerCoordinate: LatLng(_lat, _lng),
          onMapDrag: (MapDrag drag) async{
            _controller.setCenterCoordinate(drag.latLng.latitude, drag.latLng.longitude);
            await _getAddress(drag.latLng.latitude, drag.latLng.longitude);
          },
          onMapClick: (LatLng latLng) async{
            _controller.setCenterCoordinate(latLng.latitude, latLng.longitude);
            await _getAddress(latLng.latitude, latLng.longitude);
          },
          onMapCreated: (controller) async{
            _controller = controller;
            await controller.showMyLocation(true);
            await controller.setZoomLevel(17);
//            _controller?.setMapDragListener((drag) async{
//              //_controller.clearMarkers();
//
//            });
//            _controller?.setMapClickListener((latLng) async{
//              //_controller.clearMarkers();
//
//            });
          },
        ),
