### ISSUE TITLE
驾车路径规划  返回的路径不全

### ISSUE THREAD

**Issue by hongliang211** [fluttify-project/amap_search_fluttify#16]
**插件版本**
amap_search_fluttify: ^0.3.4+97873c8
**遇到bug的平台(Android/iOS)**
Android
**描述bug**
驾车路径规划  返回的路径不全  画出来的线 断断续续
报错

PlatformException(Attempt to invoke virtual method 'com.amap.api.maps.model.Polyline com.amap.api.maps.AMap.addPolyline(com.amap.api.maps.model.PolylineOptions)' on a null object reference, null, null)

**复现步骤**

**期望行为**
希望有空尽快解决
**截图**

**flutter doctor**
v1.9.1+hotfix.6

**Comment by RImpression** [comment]
骑行路径规划也有同样的问题，希望有空能修复下，十分感谢！

**Comment by ca47** [comment]
并未发现存在这样的问题，请检查你画线的方式是否正确。最好把路径点全部获取后，再进行绘制。
