### ISSUE TITLE
之前一直在用的，更新了flutter1.12.13上用不了

### ISSUE THREAD

**Issue by yfm-pliny** [fluttify-project/amap_search_fluttify#17]
**插件版本**

**遇到bug的平台(Android/iOS)**

**描述bug**

**复现步骤**

**期望行为**

**截图**

**flutter doctor**

**Comment by yohom** [comment]
有没有什么报错信息？描述下怎么个用不了法？

**Comment by yfm-pliny** [comment]
> 有没有什么报错信息？描述下怎么个用不了法？

flutter版本：1.12.13， android版本：9 
引入插件就报错，信息:
                                                                        
Compiler message:                                                       
/Applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_search_fluttify-0.7.1+5c1b957/lib/src/ios/ios.export.g.dart:117:1: Error: 'TypeOpIOS' is expor
ted from both 'package:amap_search_fluttify/src/ios/type_op.g.dart' and 'package:amap_core_fluttify/src/ios/type_op.g.dart'.
export 'package:amap_core_fluttify/amap_core_fluttify.dart';            
^                                                                       
/Applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_search_fluttify-0.7.1+5c1b957/lib/src/dart/amap_search.dart:1187:23: Error: The method 'isAMapDrivingRouteSearchRequest' isn't defined for the class 'AMapRouteSearchBaseRequest'.
 - 'AMapRouteSearchBaseRequest' is from 'package:amap_search_fluttify/src/ios/AMapRouteSearchBaseRequest.g.dart' ('/Applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_search_fluttify-0.7.1+5c1b957/lib/src/ios/AMapRouteSearchBaseRequest.g.dart').
Try correcting the name to the name of an existing method, or defining a method named 'isAMapDrivingRouteSearchRequest'.
    if (await request.isAMapDrivingRouteSearchRequest()) {              
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                   
/Applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_search_fluttify-0.7.1+5c1b957/lib/src/dart/amap_search.dart:1189:30: Error: The method 'isAMapWalkingRouteSearchRequest' isn't defined for the class 'AMapRouteSearchBaseRequest'.
 - 'AMapRouteSearchBaseRequest' is from 'package:amap_search_fluttify/src/ios/AMapRouteSearchBaseRequest.g.dart' ('/Applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_search_fluttify-0.7.1+5c1b957/lib/src/ios/AMapRouteSearchBaseRequest.g.dart').
Try correcting the name to the name of an existing method, or defining a method named 'isAMapWalkingRouteSearchRequest'.
    } else if (await request.isAMapWalkingRouteSearchRequest()) {       
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^            
/Applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_search_fluttify-0.7.1+5c1b957/lib/src/dart/amap_search.dart:1191:30: Error: The method 'isAMapBusLineBaseSearchRequest' isn't defined for the class 'AMapRouteSearchBaseRequest'.
 - 'AMapRouteSearchBaseRequest' is from 'package:amap_search_fluttify/src/ios/AMapRouteSearchBaseRequest.g.dart' ('/Applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_search_fluttify-0.7.1+5c1b957/lib/src/ios/AMapRouteSearchBaseRequest.g.dart').
Try correcting the name to the name of an existing method, or defining a method named 'isAMapBusLineBaseSearchRequest'.
    } else if (await request.isAMapBusLineBaseSearchRequest()) {        
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^             
/Applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_search_fluttify-0.7.1+5c1b957/lib/src/dart/amap_search.dart:1193:30: Error: The method 'isAMapRidingRouteSearchRequest' isn't defined for the class 'AMapRouteSearchBaseRequest'.
 - 'AMapRouteSearchBaseRequest' is from 'package:amap_search_fluttify/src/ios/AMapRouteSearchBaseRequest.g.dart' ('/Applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_search_fluttify-0.7.1+5c1b957/lib/src/ios/AMapRouteSearchBaseRequest.g.dart').
Try correcting the name to the name of an existing method, or defining a method named 'isAMapRidingRouteSearchRequest'.
    } else if (await request.isAMapRidingRouteSearchRequest()) {        
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^             
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.                                                           
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/Applications/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 780
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildDebug'.              
> Process 'command '/Applications/flutter/bin/flutter'' finished with non-zero exit value 1
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 17s                                                     
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        24.7s
Gradle task assembleDebug failed with exit code 1

**Comment by yohom** [comment]
这是我的锅，我中午会更新一个版本处理这个问题。

**Comment by yohom** [comment]
0.7.2版本试下

**Comment by yfm-pliny** [comment]
> 0.7.2版本试下

能用了，非常感谢

**Comment by yohom** [comment]
客气，那我关闭咯。

**Comment by yfm-pliny** [comment]
谢谢，能用了。 非常感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "小山"<notifications@github.com&gt;; 
发送时间: 2019年12月31日(星期二) 中午12:11
收件人: "fluttify-project/amap_search_fluttify"<amap_search_fluttify@noreply.github.com&gt;; 
抄送: "pliny"<995165335@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [fluttify-project/amap_search_fluttify] 之前一直在用的，更新了flutter1.12.13上用不了 (#17)




0.7.2版本试下
