### ISSUE TITLE
iOS真机测试错误，关键字搜索周边失败：AMapSearchRequestDidFailWithError([])

### ISSUE THREAD

**Issue by WxxShirley** [fluttify-project/amap_search_fluttify#19]
**插件版本**amap_search_fluttify: ^0.7.4+356f11c

**遇到bug的平台(Android/iOS)** iOS 13.3 

**描述bug** 关键字搜索周边失败

**截图**
![image](https://user-images.githubusercontent.com/48085932/73712234-679e5780-4744-11ea-8c6e-3abbdb0644c5.png)

**flutter doctor**：一切正常
相关iOS端配置和AmapCore.init已经配置。
（插件amap_map_fluttify使用正常）

**Comment by WxxShirley** [comment]
已解决

**Comment by houqinzhe** [comment]
> 已解决

怎么解决的 兄台

**Comment by ananas-xxj** [comment]
可以说一下解决办法嘛

**Comment by ananas-xxj** [comment]
@houqinzhe  解决了嘛，兄台
