### ISSUE TITLE
POI 能否加入地区这个字段

### ISSUE THREAD

**Issue by smartdriver001** [fluttify-project/amap_search_fluttify#2]
POI 能否加入地区这个字段 area

**Comment by smartdriver001** [comment]
希望POI能加入businessArea 这个字段，非常感谢。。。

**Comment by yohom** [comment]
我字段已经加上去了，但是试了几个关键字搜索，搜到的商圈(businessArea)都是空字符串，不知道是我的实现有问题还是本来就是空，你可以发一个有businessArea有值的关键字吗

**Comment by yohom** [comment]
试了`万达`+`北京`的组合，android端能够搜到商圈信息，但是ios端的商圈信息为空，debug后发现sdk返回的就是空字符串<img width="368" alt="Screen Shot 2019-10-25 at 08 53 38" src="https://user-images.githubusercontent.com/10418364/67535433-2fc75300-f705-11e9-8260-587a40497e47.png">
我先上传当前版本了，如果你试了其他组合还是获取不到商圈信息的话重开这个issue吧。

**Comment by yohom** [comment]
0.2.8版本 已增加此字段
