### ISSUE TITLE
关键字查询，查询不到数据，且报异常

### ISSUE THREAD

**Issue by XZYsunny** [fluttify-project/amap_search_fluttify#38]
**插件版本**
amap_search_fluttify: ^0.14.0
**遇到bug的平台(Android/iOS)**
iOS
**描述bug**
关键字查询，没有传city字段查询不到数据
**复现步骤**

**期望行为**

**截图**
![image](https://user-images.githubusercontent.com/8319200/93977594-4fe81200-fdad-11ea-8586-50379166c568.png)
![image](https://user-images.githubusercontent.com/8319200/93977659-67bf9600-fdad-11ea-912d-a154d1e94d7f.png)
![image](https://user-images.githubusercontent.com/8319200/93979345-cbe35980-fdaf-11ea-9d48-b6e0e2ad2863.png)

**flutter doctor**
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale
    zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
[✓] Connected device (2 available)

• No issues found!

**Comment by XZYsunny** [comment]
可能是关键字的问题，但是那个异常不知道是咋回事

**Comment by ananas-xxj** [comment]
有找到原因嘛
