### ISSUE TITLE
导航功能

### ISSUE THREAD

**Issue by lyy1005664097** [fluttify-project/amap_search_fluttify#7]
你好，驾车、骑行、和步行的线路规划返回的是一些路径列表，能不能像高德地图app中那样在地图上显示规划的路径图，然后可以选择规划的路径图进行导航？

**Comment by yohom** [comment]
你把搜索出来的结果放到amap_map_fluttify里去画出来就行了

**Comment by lyy1005664097** [comment]
我现在把路径规划图在地图上画出来了，怎么开启导航呢

**Comment by yohom** [comment]
导航要么集成高德的导航组件（现在没有实现这个功能），要么使用`url_launcher`直接打开各个平台的高德地图app，详细直接百度吧。
