### ISSUE TITLE
添加最新版本的项目跑不起来 0.2.10+70bd548 

### ISSUE THREAD

**Issue by AOWOAO** [fluttify-project/amap_search_fluttify#8]
**插件版本**

 0.2.10+70bd548

**描述bug**

添加最新版本的项目跑不起来

**复现步骤**

**期望行为**

**截图**

![微信截图_20191104160500](https://user-images.githubusercontent.com/25810208/68106609-1f8d5000-ff1d-11e9-8252-e0ae7fda6dad.png)
![微信截图_20191104160535](https://user-images.githubusercontent.com/25810208/68106616-26b45e00-ff1d-11e9-8902-8d712b52c578.png)

**flutter doctor**

**Comment by yohom** [comment]
这种情况，去`$flutter_root/.pub-cache`下清掉旧版本就可以了。参考https://github.com/fluttify-project/amap_map_fluttify/issues/26#issuecomment-548693045

**Comment by AOWOAO** [comment]
清掉旧版本后, 已解决, 谢谢
